"""Polish payday lender (instytucje pożyczkowe) database.

Comprehensive list of ~475 companies registered as lending institutions
in Poland (KNF registry). Used for AML transaction classification.

Source: KNF Rejestr Instytucji Pożyczkowych
"""

from __future__ import annotations

import re
from typing import List, Optional, Set, Tuple


# ============================================================
# PAYDAY LENDER BRAND NAMES
# Normalized brand names (without legal suffixes like Sp. z o.o.)
# ============================================================

PAYDAY_LENDER_NAMES: Set[str] = {
    "A-LEX",
    "AASA",
    "ABACUS FINANCE",
    "AD FINANCE",
    "AD INVEST",
    "AGART FINANSE",
    "AGENCJA FINANSOWA PROFIT",
    "AGNOS",
    "AIQLABS",
    "AJL-FINANSE",
    "ALEGOTÓWKA",
    "ALFA FINANCE",
    "ALFA INVESTMENTS",
    "ALFAKREDYT",
    "ALLIANCE FINANCE",
    "ALTUS CREDIT",
    "ALWIS FINANSE",
    "AM CAPITAL",
    "AM KREDYT",
    "AMBULANCE BANKING",
    "AMG GOLD",
    "ANMAROT",
    "AP BROKER",
    "APJD FINANSE",
    "ARENA FINANCE",
    "ARGENTUM CAPITAL",
    "ARGO PROFIT",
    "ART-MA",
    "ASETIA",
    "ASFBAL",
    "ASPER",
    "ATIZ",
    "ATJM GROUP",
    "ATS FINANSE",
    "AUTOKAPITAL.PL 2",
    "AvaFin Poland",
    "AVALIA",
    "AVIOR FINANCE",
    "AXCESS FINANCIAL POLAND",
    "AXOR CAPITAL GROUP",
    "B &W INTERNATIONAL INVESTMENT",
    "BALT CREDIT",
    "BANKNOT",
    "BARY BARTŁOMIEJ DZIEWIATOWSKI",
    "BERG SOLUTIONS",
    "BETA INVESTMENTS",
    "BEZBANQ.PL",
    "BF CAPITAL",
    "BIO FINANSE",
    "BIURO KREDYTOWE PROFIT",
    "BIURO POŚREDNICTWA",
    "BIZON CAPITAL",
    "BLEND SCORE",
    "BLENDER POLAND",
    "BLUE FINANCE POLSKA",
    "BOJAROWICZ POŻYCZKI",
    "BUSINESS EVOLUTION",
    "BW\" FINANSE",
    "C2FINANCE",
    "CAPITAL SERVICE",
    "CAPITAL SYSTEM",
    "CAPITAL4YOU",
    "CARD FINANCE",
    "CARDINA",
    "CASH POLSKA",
    "CASH SERVICE 4 HOME",
    "CASHPER",
    "CASHSPORT.pl",
    "CCREDIT",
    "CENTRUM POŻYCZKOWO KREDYTOWE",
    "CENTRUM ROZWIĄZAŃ KREDYTOWYCH",
    "CHWILA-MOMENT",
    "CINTRA NETWORK",
    "CK MONEY",
    "COMFORT CREDIT",
    "CONNECT FINANCE",
    "CONTANTE",
    "CREDIBUY.COM",
    "CREDIS POLSKA",
    "CREDISSIMO PLUS",
    "CREDISSIMO POLSKA",
    "CREDIT 123",
    "CREDITSTAR POLAND",
    "CREDITYOU",
    "CROSS LOAN",
    "CTE FINANSE",
    "CURRENCY LENDING",
    "D&D FINANCIAL GROUP",
    "DAIGLOB",
    "DELTA KING",
    "DENAJRO",
    "DIGITALFIN",
    "DJAFINANSE",
    "DJK FINANCE",
    "DOBRA KASA",
    "DOBRA MONETA",
    "DOBRY KREDYT",
    "DR POŻYCZKA",
    "DREW-TRADE",
    "DUCATOS",
    "DUKAT FINANSE",
    "DUO FINANCE",
    "DZIESIĄTKA FINANSE",
    "E-FINANCE",
    "EASY MONEY",
    "EASY RATY",
    "EBANCO",
    "EDEA II POLSKA",
    "EDEN FINANCE",
    "EFIMEA",
    "EKASSA",
    "EKSPRESS FINANSE",
    "EKSTRAKASA",
    "EMPIRE FINANSE",
    "EMPRESTIMO",
    "EPEER",
    "ERBEO SERVICES",
    "ERIDU POŻYCZKI",
    "ESERO",
    "ETO KAVKAZ GROUP",
    "EURO PROVIDUS",
    "EVEREST FINANSE",
    "EXPRESS FINANCE",
    "EXPRESS LOAN",
    "EXPRESS PROFIT",
    "EXTRA PORTFEL",
    "FALCON CAPITALS",
    "FAST CASH",
    "FELPOL UBEZPIECZENIA I FINANSE",
    "FENIKO",
    "FENIKO FINANSE",
    "FENIKS POŻYCZKI",
    "FERRATUM",
    "FIDEM PLUS",
    "FIDO FINANSE",
    "FILARUM",
    "FILENTIA",
    "FINANCIAL BENEFITS",
    "FINANCIAL SAFETY",
    "FINANCIAL WORLD",
    "FINANSE DLA KAŻDEGO A-Z",
    "FINANSEC",
    "FINAR",
    "FINGO CAPITAL",
    "FINPOMOC",
    "FINSTAL",
    "FINTOPIA TECHNOLOGY",
    "FINVA",
    "FIRST ONE",
    "FLASH INVESTMENT GROUP",
    "FLEXEE BENEFITS",
    "FLOTA FINANSOWA",
    "FORDICH",
    "FORGE GROUP",
    "FORIAL",
    "FOX MONEY",
    "FREEDOM FINANCIAL",
    "FUNDUSZ BPC",
    "FUNDUSZ HIPOTECZNY FILAR",
    "FUNDUSZ MIKRO",
    "FUNDUSZ POŻYCZKOWO-PORĘCZENIOWY GRANT",
    "FUNDUSZ POŻYCZKOWY B&B",
    "GD MONEY",
    "GKI Gros Kapitał Invest",
    "GLOBAL FINANSE",
    "GLOBAL INVESTMENT",
    "GLOBMONEY",
    "GOCASH MG",
    "GOOD GUYS",
    "GRANTIS",
    "GROS KAPITAŁ GROUP",
    "GROS KAPITAŁ HOLDING",
    "GRUPA FINANSOWA AS",
    "GRUPA FINANSOWA EXPERT",
    "GRUPA FINANSOWA JPP",
    "GRUPA FINANSOWA KAPITAŁ",
    "GRUPA ITIM",
    "GRUPA KAPITAŁOWA GWARANT",
    "GRUPA KAPITAŁOWA PARKMAR INKASSO",
    "GRUPA RAFDEN",
    "GRYFFIN POLSKA",
    "GTW FINANSE",
    "GWARANT24",
    "HAPILOANS",
    "HAPIPOŻYCZKI",
    "HELP INKASSO",
    "HERMES POŻYCZKI",
    "HOLDCASH",
    "HOPLI POŻYCZKI",
    "HORTUS FINANCE",
    "HSZ FINANCE",
    "HUZAR POŻYCZKI",
    "iCREDIT",
    "ID FINANCE POLAND",
    "INCAPITAL",
    "INCREDIT",
    "INKASO CITY",
    "INSTAFIN",
    "INSTANT MONEY",
    "INTELLECT MONEY",
    "INVESYSTEM",
    "INVIFINANCE",
    "INWESTYCJE BPC",
    "IPF POLSKA",
    "JANALI",
    "JJK CREDIT",
    "JK Investment Group",
    "JK POŻYCZKI",
    "JOKAN LIMITED",
    "JURAN GOLD",
    "KANCELARIA FINANSOWA LEGE ARTIS",
    "KANCELARIA WINDYKACYJNA \"KOMPENSATOR",
    "KaPi HOME FINANCE",
    "KARAT PL",
    "KASA24H",
    "KASEO",
    "KHG FINANSE",
    "KIM FINANCE",
    "KLASTOPIN",
    "KLM - CENTRUM DORADZTWA I USŁUG",
    "KOMEN",
    "KONSORCJUM FINANSOWE",
    "KRAJOWE CENTRUM DORADZTWA FINANSOWEGO",
    "KRAJOWE CENTRUM INNOWACJI",
    "KRAJOWE CENTRUM POŻYCZKOWE",
    "KRAJOWY FUNDUSZ FINANSOWY",
    "KREDICO2000",
    "KREDITECH POLSKA",
    "KREDOO",
    "KREDYT POINT",
    "KREDYT POLSKI",
    "KREDYTPLUS 2",
    "KREDYTY PARTNERSKIE",
    "KREOS",
    "KUKI",
    "KUKUŁKA-FINANSE",
    "KZK KREDYTY",
    "LBD888",
    "LENDBUY",
    "LENDER24",
    "LENDON",
    "LENS FINANCE",
    "LEX POŻYCZKA",
    "LIBERIS POLSKA",
    "LIMA 500",
    "LIME-KREDYT",
    "LIMIT POŻYCZKA",
    "LJ FINANSE",
    "LOAN ME",
    "LOOK POŻYCZKA",
    "LS FINANCE",
    "LS NEXUM",
    "LTU FINANCE",
    "LUKAS POLSKA",
    "LUKASPOINT",
    "M2 POLSKA",
    "MARKTON",
    "MARSHAL LION CONSULTING",
    "MATPOL FINANSE",
    "MAZOWIECKI FUNDUSZ POŻYCZKOWY",
    "MAZOWIECKIE CENTRUM FINANSOWE",
    "MAŁY-KREDYT.PL",
    "MB BUSINESS SUPPORT",
    "MBR FINANCE",
    "MDP FINANCE",
    "MEDICAL FINANCE GROUP",
    "MEDYCZNA POŻYCZKA",
    "MEGA FINANSE MF",
    "MERCURY FINANCIAL",
    "MEWA FINANSE",
    "MG INVESTMENT",
    "MIKRO-FINANSE",
    "MIKROKASA",
    "MILDUM",
    "MILDUM FINANSE",
    "MILIOT",
    "MILOAN POLSKA",
    "MILUCREDIT",
    "MINICREDIT",
    "MMCREDIT",
    "MOBILUM PAY",
    "MOGAN INVEST",
    "MOMENT FINANSE",
    "MONEY BOOM",
    "MONEY PROGRES",
    "MONEY TRADE GROUP",
    "MOZIPO",
    "MSG INVEST",
    "MSKREDYT",
    "MULTICA",
    "MULTIFINANS",
    "MY-INVEST",
    "NEKSUM",
    "NET GOTÓWKA",
    "NETCREDIT",
    "NEWCREDIT",
    "NEXT CREDIT",
    "NEXXO",
    "NG PARTNERS",
    "NINIWA POŻYCZKI",
    "NORDBALTICA POLSKA",
    "NORDECUM",
    "NORTE FINANSE",
    "NOVINA",
    "NOVUM FINANCE",
    "O!KASSA",
    "ODF-OBIEKTYWNE DORADZTWO FINANSOWE",
    "ODPOWIEDZIALNE FINANSE",
    "OMEGA FINANSE",
    "OMNICO",
    "OMNIGRANT FINANSE",
    "ONLINE POŻYCZKA",
    "OPUS CREDIT",
    "OSKAR DTS",
    "OTSV",
    "P.H.U. CALYPSO",
    "P.H.U. NOVO",
    "PAN POŻYCZKA",
    "PANDA FINANSE",
    "PARASOL CASH",
    "PARTNER POŻYCZKI",
    "PAYDAYLEND",
    "PAYHOLDING INTERNATIONAL",
    "PAYPO",
    "PAYTREE",
    "PBSPARTNER",
    "PBSPARTNER FINANSE I UBEZPIECZENIA",
    "PEWNA KASA",
    "PIENIĄŻEK-POŻYCZKI",
    "PIK FINANSE",
    "PLATFORMA KREDYTOWA",
    "PLUS GOTÓWKA",
    "PLUSKASA",
    "POLAPART",
    "POLCREDIT",
    "POLSKA KASA",
    "POLSKA PLATFORMA FINANSOWA",
    "POLSKI - KREDYT",
    "POLSKI HOLDING KAPITAŁOWY",
    "POLSKI LOMBARD",
    "POLSKIE BIURO POŻYCZKOWE GWARANT",
    "POLSKIE CENTRUM POŻYCZKOWE",
    "POLSKIE FINANSE",
    "POLSKIE FINANSE PRZEMYSŁAW MIECZKOWSKI",
    "POLSKIE TOWARZYSTWO FINANSOWE GWARANT",
    "POLSKIE TOWARZYSTWO POŻYCZKOWE",
    "POMARAŃCZA OWOCNE POŻYCZKI",
    "POSO-TELIS",
    "POZYCZKOMAT",
    "POŚREDNICTWO FINANSOWE \"JOCKER",
    "POŻYCZ TU",
    "POŻYCZKA PIENIĘDZY",
    "POŻYCZKA REFINANS",
    "POŻYCZKAPORTAL",
    "PREMIUM POŻYCZKI",
    "PREMIUM-MED FINANSE",
    "PRESTAMO CREDIT",
    "PRIMASTAR",
    "PRO DOMO",
    "PRO DOMO FINANSE",
    "PROCAPITA",
    "PROFI CREDIT POLSKA",
    "PROFINANS",
    "PROFINET",
    "PROGRES FINANSE",
    "PROMEDIAL",
    "PROMETEUSZ FINANSE",
    "PROSPERIAL",
    "PROSPERO",
    "PROSTA POŻYCZKA",
    "PROSTYKREDYT",
    "PROVEMA",
    "PROVIDENT POLSKA",
    "PRZEDSIĘBIORSTWO WIELOBRANŻOWE VITA",
    "PSF LOANS",
    "PSZCZÓŁKA PIECHOCCY",
    "PZU CASH",
    "RAJ CAPITAL INVEST",
    "RAPID FINANCE POLSKA",
    "RATKA",
    "REFINI.PL",
    "RELIANCE CAPITAL",
    "RENOMA USŁUGI FINANSOWE",
    "REVO TECHNOLOGIES",
    "REVOLINO",
    "REWERS",
    "REWERTIS",
    "Rh INVEST",
    "RODZINNE CHWILÓWKI",
    "RODZINNE POŻYCZKI",
    "RODZINNE TOWARZYSTWO FINANSOWE FINGRAM",
    "RUPI FINANCE",
    "SAGITTA CREDIT",
    "SANE CAPITAL",
    "SANTANDER CONSUMER FINANCIAL SOLUTIONS",
    "SANTANDER F24",
    "SHEKELS",
    "SKARBIEC POLSKI",
    "SKYCASH FINANCE",
    "SMARTNEY",
    "SMARTNEY GRUPA ONEY",
    "SOLCREDIT",
    "SOLVEN FINANCE",
    "SOLVEN FUNDS",
    "SOONLY FINANCE",
    "SPAR FINANSE",
    "SPARTA FINANCE",
    "SPECTRUM FINANSE DLA FIRM",
    "SPEED CASH POLSKA",
    "SPEED MONEY",
    "SPEEDY CASH POLSKA",
    "SUBTENO",
    "SUKURS FINANSE",
    "SUPERCASH",
    "SUPERGROSZ",
    "SWIFT CASH",
    "SWISS CREDIT SUPPORT",
    "SYMMETRICAL FINANCIALS",
    "SZYBKA GOTÓWKA",
    "SZYBKA POŻYCZKA",
    "SZYBKA POŻYCZKA - ARTEX",
    "SZYBKA POŻYCZKA POLSKA",
    "SZYBKA POŻYCZKA POLSKA PLUS",
    "SZYBKASA",
    "SZYBKI KREDYT",
    "T&T PARTNERS",
    "TAIMEN POLSKA",
    "TAKTO FINANSE",
    "TALAROS",
    "TANI KREDYT",
    "TAYLOR FINANCE CAPITAL",
    "TEC-INVEST",
    "THOREX",
    "TMK FINANCE",
    "TOP MONEY",
    "TREFLE CREDIT",
    "TRIBAG",
    "TRIFY POŻYCZKI",
    "TRUST CAPITAL",
    "TRYPAY LATER",
    "TRZYD CAPITAL",
    "TUSUMI",
    "TWISTO POLSKA",
    "UŁAN POŻYCZKI",
    "VANCO INWESTYCJE",
    "VFUND",
    "VIA PAYMENTS UAB",
    "VIA SMS PL",
    "VIPPO",
    "VISSET",
    "VIVUS",
    "VIVVO",
    "VIZARD FINANCE",
    "VULCAN FINANCE",
    "WACREDIT",
    "WANDOO",
    "WGIF",
    "WIERZYCIEL",
    "WILARO",
    "WONGA.PL",
    "WRB INVEST",
    "WT FINANSE 24",
    "WYGODNA RATA.PL",
    "WĘGLIŃSKI INVEST",
    "YES FINANCE",
    "Z4.MONEY",
    "ZALICZKA",
    "ZAPLO",
    "ZLOTOWKA",
    "ZOEFIN PL",
    "ZWW",
    "ZŁOTÓWKA BIS",
    "ZŁOTÓWKA DUO",
    "ZŁOTÓWKA THREE",
    "ŚLIMAK FINANCE",
}


# ============================================================
# COMPILED MATCHING ENGINE
# ============================================================

_compiled_patterns: Optional[List[Tuple[str, re.Pattern]]] = None


def _build_patterns() -> List[Tuple[str, re.Pattern]]:
    """Compile regex patterns from brand names (longest first)."""
    patterns = []
    for name in sorted(PAYDAY_LENDER_NAMES, key=len, reverse=True):
        escaped = re.escape(name)
        escaped = escaped.replace(r"\ ", r"\s+")
        try:
            pat = re.compile(r"\b" + escaped + r"\b", re.IGNORECASE)
            patterns.append((name, pat))
        except re.error:
            pass
    return patterns


def _ensure_compiled():
    global _compiled_patterns
    if _compiled_patterns is None:
        _compiled_patterns = _build_patterns()


def is_payday_lender(text: str) -> bool:
    """Check if text contains a known payday lender name."""
    if not text:
        return False
    _ensure_compiled()
    for _name, pat in _compiled_patterns:
        if pat.search(text):
            return True
    return False


def match_payday_lender(text: str) -> Optional[str]:
    """Return the matched payday lender brand name, or None."""
    if not text:
        return None
    _ensure_compiled()
    for name, pat in _compiled_patterns:
        if pat.search(text):
            return name
    return None
