"""Complete gazetteer of Polish cities (miasta w Polsce) for location extraction.

Contains ALL cities with municipal rights in Poland (~960 cities across all 16
voivodeships), plus popular tourist/resort towns and ASCII transliterations of
names containing Polish diacritics.

Sources: GUS (Central Statistical Office) list of cities with municipal rights.

Naming conventions:
- All entries are lowercase.
- Multi-word cities preserve spaces: "nowy sącz".
- Hyphenated cities preserve hyphens: "bielsko-biała".
- For every name containing Polish diacritics (ą, ć, ę, ł, ń, ó, ś, ź, ż),
  an ASCII-transliterated variant is also included.
- Sorted by voivodeship, then alphabetically within each voivodeship.
"""

POLISH_CITIES = {
    # ==================================================================
    # Województwo dolnośląskie (Dolnośląskie / Lower Silesian)
    # ==================================================================
    "bielawa",
    "bierutów", "bierutow",
    "bogatynia",
    "boguszów-gorce", "boguszow-gorce", "boguszów gorce", "boguszow gorce",
    "bolków", "bolkow",
    "bolesławiec", "boleslawiec",
    "brzeg dolny",
    "bystrzyca kłodzka", "bystrzyca klodzka",
    "chojnów", "chojnow",
    "duszniki-zdrój", "duszniki-zdroj", "duszniki zdrój", "duszniki zdroj",
    "dzierżoniów", "dzierzoniow",
    "głogów", "glogow",
    "głuszyca",  "gluszyca",
    "góra", "gora",
    "gryfów śląski", "gryfow slaski",
    "jawor",
    "jaworzyna śląska", "jaworzyna slaska",
    "jedlina-zdrój", "jedlina-zdroj", "jedlina zdrój", "jedlina zdroj",
    "jelcz-laskowice",
    "jelenia góra", "jelenia gora",
    "jugowice",
    "kamienna góra", "kamienna gora",
    "karpacz",
    "kąty wrocławskie", "katy wroclawskie",
    "kłodzko", "klodzko",
    "kowary",
    "kudowa-zdrój", "kudowa-zdroj", "kudowa zdrój", "kudowa zdroj",
    "lądek-zdrój", "ladek-zdroj", "lądek zdrój", "ladek zdroj",
    "legnica",
    "leśna", "lesna",
    "lubań", "luban",
    "lubin",
    "lubomierz",
    "lwówek śląski", "lwowek slaski",
    "mieroszów", "mieroszow",
    "milicz",
    "mirsk",
    "międzybórz", "miedzyborz",
    "międzylesie", "miedzylesie",
    "nowa ruda",
    "nowogrodziec",
    "oborniki śląskie", "oborniki slaskie",
    "oleśnica", "olesnica",
    "oława", "olawa",
    "piechowice",
    "pieszyce",
    "piława górna", "pilawa gorna",
    "polanica-zdrój", "polanica-zdroj", "polanica zdrój", "polanica zdroj",
    "polkowice",
    "prusice",
    "przemków", "przemkow",
    "radków", "radkow",
    "sobótka", "sobotka",
    "strzegom",
    "strzelin",
    "syców", "sycow",
    "szczawno-zdrój", "szczawno-zdroj", "szczawno zdrój", "szczawno zdroj",
    "szczytna",
    "szklarska poręba", "szklarska poreba",
    "środa śląska", "sroda slaska",
    "świdnica", "swidnica",
    "świebodzice", "swiebodzice",
    "świeradów-zdrój", "swieradow-zdroj", "świeradów zdrój", "swieradow zdroj",
    "świerzawa", "swierzawa",
    "trzebnica",
    "twardogóra", "twardogora",
    "wałbrzych", "walbrzych",
    "wąsosz", "wasosz",
    "węgliniec", "wegliniec",
    "wiązów", "wiazow",
    "wleń", "wlen",
    "wojcieszów", "wojcieszow",
    "wołów", "wolow",
    "wrocław", "wroclaw",
    "zawidów", "zawidow",
    "ząbkowice śląskie", "zabkowice slaskie",
    "ziębice", "ziebice",
    "zgorzelec",
    "złotoryja", "zlotoryja",
    "złoty stok", "zloty stok",
    "żarów", "zarow",
    "żmigród", "zmigrod",

    # ==================================================================
    # Województwo kujawsko-pomorskie (Kuyavian-Pomeranian)
    # ==================================================================
    "aleksandrów kujawski", "aleksandrow kujawski",
    "barcin",
    "brodnica",
    "bydgoszcz",
    "chełmno", "chelmno",
    "chełmża", "chelmza",
    "ciechocinek",
    "czeladź", "czeladz",
    "dobrzyń nad wisłą", "dobrzyn nad wisla",
    "gniewkowo",
    "golub-dobrzyń", "golub-dobrzyn", "golub dobrzyń", "golub dobrzyn",
    "górzno", "gorzno",
    "grudziądz", "grudziadz",
    "inowrocław", "inowroclaw",
    "janikowo",
    "jabłonowo pomorskie", "jablonowo pomorskie",
    "kamień krajeński", "kamien krajenski",
    "koronowo",
    "kowalewo pomorskie",
    "kruszwica",
    "lipno",
    "łasin", "lasin",
    "mogilno",
    "nakło nad notecią", "naklo nad notecia",
    "nieszawa",
    "nowe",
    "pakość", "pakosc",
    "radziejów", "radziejow",
    "radzyń chełmiński", "radzyn chelminski",
    "rypin",
    "sępólno krajeńskie", "sepolno krajenskie",
    "skępe", "skepe",
    "solec kujawski",
    "strzelno",
    "szubin",
    "świecie", "swiecie",
    "toruń", "torun",
    "tuchola",
    "wąbrzeźno", "wabrzezno",
    "włocławek", "wloclawek",
    "żnin", "znin",

    # ==================================================================
    # Województwo lubelskie (Lublin)
    # ==================================================================
    "annopol",
    "biała podlaska", "biala podlaska",
    "biłgoraj", "bilgoraj",
    "bychawa",
    "chełm", "chelm",
    "dęblin", "deblin",
    "frampol",
    "hrubieszów", "hrubieszow",
    "janów lubelski", "janow lubelski",
    "józefów", "jozefow",
    "kazimierz dolny",
    "krasnobród", "krasnobrod",
    "krasnystaw",
    "kraśnik", "krasnik",
    "lubartów", "lubartow",
    "lublin",
    "łaszczów", "laszczow",
    "łęczna", "leczna",
    "łuków", "lukow",
    "międzyrzec podlaski", "miedzyrzec podlaski",
    "modliborzyce",
    "nałęczów", "naleczow",
    "opole lubelskie",
    "parczew",
    "poniatowa",
    "puławy", "pulawy",
    "radzyń podlaski", "radzyn podlaski",
    "rejowiec fabryczny",
    "ryki",
    "stoczek łukowski", "stoczek lukowski",
    "szczebrzeszyn",
    "świdnik", "swidnik",
    "terespol",
    "tomaszów lubelski", "tomaszow lubelski",
    "tyszowce",
    "włodawa", "wlodawa",
    "zamość", "zamosc",
    "zwierzyniec",

    # ==================================================================
    # Województwo lubuskie (Lubusz)
    # ==================================================================
    "babimost",
    "bytom odrzański", "bytom odrzanski",
    "cybinka",
    "czerwieńsk", "czerwiensk",
    "dobiegniew",
    "drezdenko",
    "gozdnica",
    "gubin",
    "iłowa", "ilowa",
    "jasień", "jasien",
    "kargowa",
    "kostrzyn nad odrą", "kostrzyn nad odra",
    "kożuchów", "kozuchow",
    "krosno odrzańskie", "krosno odrzanskie",
    "lubsko",
    "łęknica", "leknica",
    "małomice", "malomice",
    "międzyrzecz", "miedzyrzecz",
    "nowa sól", "nowa sol",
    "nowe miasteczko",
    "nowogród bobrzański", "nowogrod bobrzanski",
    "ośno lubuskie", "osno lubuskie",
    "rzepin",
    "sława", "slawa",
    "skwierzyna",
    "strzelce krajeńskie", "strzelce krajenskie",
    "sulechów", "sulechow",
    "sulęcin", "sulecin",
    "szlichtyngowa",
    "szprotawa",
    "świebodzin", "swiebodzin",
    "torzym",
    "trzciel",
    "wschowa",
    "zbąszynek", "zbaszynek",
    "zielona góra", "zielona gora",
    "żagań", "zagan",
    "gorzów wielkopolski", "gorzow wielkopolski",
    "żary", "zary",

    # ==================================================================
    # Województwo łódzkie (Łódź / Lodz)
    # ==================================================================
    "aleksandrów łódzki", "aleksandrow lodzki",
    "bełchatów", "belchatow",
    "biała rawska", "biala rawska",
    "błaszki", "blaszki",
    "brzeziny",
    "drzewica",
    "działoszyn", "dzialoszyn",
    "głowno", "glowno",
    "kamieńsk", "kamiensk",
    "koluszki",
    "konstantynów łódzki", "konstantynow lodzki",
    "krośniewice", "krosniewice",
    "kutno",
    "lask", "łask",
    "łęczyca", "leczyca",
    "łowicz", "lowicz",
    "łódź", "lodz",
    "opoczno",
    "ozorków", "ozorkow",
    "pabianice",
    "pajęczno", "pajeczno",
    "piotrków trybunalski", "piotrkow trybunalski",
    "poddębice", "poddebice",
    "przedbórz", "przedborz",
    "radomsko",
    "rawa mazowiecka",
    "rzgów", "rzgow",
    "sieradz",
    "skierniewice",
    "stryków", "strykow",
    "sulejów", "sulejow",
    "szadek",
    "tomaszów mazowiecki", "tomaszow mazowiecki",
    "tuszyn",
    "uniejów", "uniejow",
    "warta",
    "wieluń", "wielun",
    "wieruszów", "wieruszow",
    "wolbórz", "wolborz",
    "zduńska wola", "zdunska wola",
    "zelów", "zelow",
    "zgierz",
    "złoczew", "zloczew",
    "żychlin", "zychlin",

    # ==================================================================
    # Województwo małopolskie (Lesser Poland / Małopolska)
    # ==================================================================
    "alwernia",
    "andrychów", "andrychow",
    "bochnia",
    "brzesko",
    "brzeszcze",
    "bukowno",
    "chełmek", "chelmek",
    "chrzanów", "chrzanow",
    "ciężkowice", "ciezkowice",
    "czchów", "czchow",
    "dąbrowa tarnowska", "dabrowa tarnowska",
    "dobczyce",
    "grybów", "grybow",
    "jordanów", "jordanow",
    "kalwaria zebrzydowska",
    "kazimierza wielka",
    "kęty", "kety",
    "kraków", "krakow",
    "krzeszowice",
    "libiąż", "libiaz",
    "limanowa",
    "maków podhalański", "makow podhalanski",
    "miechów", "miechow",
    "mszana dolna",
    "muszyna",
    "myślenice", "myslenice",
    "niepołomice", "niepolomice",
    "nowe brzesko",
    "nowy sącz", "nowy sacz",
    "nowy targ",
    "nowy wiśnicz", "nowy wisnicz",
    "olkusz",
    "oświęcim", "oswiecim",
    "piwniczna-zdrój", "piwniczna-zdroj", "piwniczna zdrój", "piwniczna zdroj",
    "proszowice",
    "rabka-zdrój", "rabka-zdroj", "rabka zdrój", "rabka zdroj",
    "ryglice",
    "skała", "skala",
    "skawina",
    "słomniki", "slomniki",
    "stary sącz", "stary sacz",
    "sucha beskidzka",
    "sułkowice", "sulkowice",
    "szczawnica",
    "szczucin",
    "świątniki górne", "swiatniki gorne",
    "tarnów", "tarnow",
    "trzebinia",
    "tuchów", "tuchow",
    "wadowice",
    "wieliczka",
    "wojnicz",
    "wolbrom",
    "zakopane",
    "zakliczyn",
    "zator",
    "żabno", "zabno",

    # ==================================================================
    # Województwo mazowieckie (Masovian / Mazowsze)
    # ==================================================================
    "białobrzegi", "bialobrzegi",
    "błonie", "blonie",
    "brwinów", "brwinow",
    "ciechanów", "ciechanow",
    "constancin-jeziorna",
    "drobin",
    "garwolin",
    "gąbin", "gabin",
    "glinojeck",
    "góra kalwaria", "gora kalwaria",
    "grodzisk mazowiecki",
    "grójec", "grojec",
    "halinów", "halinow",
    "iłża", "ilza",
    "józefów", "jozefow",
    "kałuszyn", "kaluszyn",
    "karczew",
    "kobyłka", "kobylka",
    "konstancin-jeziorna",
    "kosów lacki", "kosow lacki",
    "kozienice",
    "legionowo",
    "lipsko",
    "łaskarzew", "laskarzew",
    "łochów", "lochow",
    "łomianki", "lomianki",
    "łosice", "losice",
    "maków mazowiecki", "makow mazowiecki",
    "marki",
    "milanówek", "milanowek",
    "mińsk mazowiecki", "minsk mazowiecki",
    "mława", "mlawa",
    "mogielnica",
    "mordy",
    "mszczonów", "mszczonow",
    "myszyniec",
    "nasielsk",
    "nowy dwór mazowiecki", "nowy dwor mazowiecki",
    "ostrołęka", "ostroleka",
    "ostrów mazowiecka", "ostrow mazowiecka",
    "otwock",
    "ożarów mazowiecki", "ozarow mazowiecki",
    "piaseczno",
    "piastów", "piastow",
    "pilawa",
    "pionki",
    "płock", "plock",
    "płońsk", "plonsk",
    "podkowa leśna", "podkowa lesna",
    "pomiechówek", "pomiechowek",
    "pruszków", "pruszkow",
    "przasnysz",
    "przysucha",
    "pułtusk", "pultusk",
    "radom",
    "radzymin",
    "różan", "rozan",
    "serock",
    "siedlce",
    "sierpc",
    "skaryszew",
    "sochaczew",
    "sokołów podlaski", "sokolow podlaski",
    "sulejówek", "sulejowek",
    "szydłowiec", "szydlowiec",
    "tarczyn",
    "tłuszcz", "tluszcz",
    "warszawa",
    "węgrów", "wegrow",
    "wołomin", "wolomin",
    "wyszków", "wyszkow",
    "wyszogród", "wyszogrod",
    "wyśmierzyce", "wysmierzyce",
    "zakroczym",
    "ząbki", "zabki",
    "zielonka",
    "zwoleń", "zwolen",
    "żelechów", "zelechow",
    "żuromin", "zuromin",
    "żyrardów", "zyrardow",

    # ==================================================================
    # Województwo opolskie (Opole)
    # ==================================================================
    "biała", "biala",
    "brzeg",
    "byczyna",
    "dobrodzień", "dobrodzien",
    "głogówek", "glogowek",
    "głubczyce", "glubczyce",
    "głuchołazy", "glucholazy",
    "gorzów śląski", "gorzow slaski",
    "gogolin",
    "kędzierzyn-koźle", "kedzierzyn-kozle", "kędzierzyn koźle", "kedzierzyn kozle",
    "kietrz",
    "kluczbork",
    "kolonowskie",
    "korfantów", "korfantow",
    "krapkowice",
    "leśnica", "lesnica",
    "lewin brzeski",
    "namysłów", "namyslow",
    "niemodlin",
    "nysa",
    "olesno",
    "opole",
    "otmuchów", "otmuchow",
    "ozimek",
    "paczków", "paczkow",
    "praszka",
    "prudnik",
    "prószków", "proszkow",
    "strzelce opolskie",
    "strzeleczki",
    "ujazd",
    "wołczyn", "wolczyn",
    "zawadzkie",
    "zdzieszowice",

    # ==================================================================
    # Województwo podkarpackie (Subcarpathian)
    # ==================================================================
    "baranów sandomierski", "baranow sandomierski",
    "błażowa", "blazowa",
    "boguchwała", "boguchwala",
    "brzozów", "brzozow",
    "cieszanów", "cieszanow",
    "dębica", "debica",
    "dubiecko",
    "dynów", "dynow",
    "głogów małopolski", "glogow malopolski",
    "iwonicz-zdrój", "iwonicz-zdroj", "iwonicz zdrój", "iwonicz zdroj",
    "jarosław", "jaroslaw",
    "jasło", "jaslo",
    "jedlicze",
    "kańczuga", "kanczuga",
    "kolbuszowa",
    "krosno",
    "lesko",
    "leżajsk", "lezajsk",
    "lubaczów", "lubaczow",
    "łańcut", "lancut",
    "mielec",
    "narol",
    "nisko",
    "nowa dęba", "nowa deba",
    "nowa sarzyna",
    "oleszyce",
    "pilzno",
    "przemyśl", "przemysl",
    "przeworsk",
    "radymno",
    "radomyśl wielki", "radomysl wielki",
    "ropczyce",
    "rudnik nad sanem",
    "rymanów", "rymanow",
    "rzeszów", "rzeszow",
    "sanok",
    "sędziszów małopolski", "sedziszow malopolski",
    "sieniawa",
    "sokołów małopolski", "sokolow malopolski",
    "stalowa wola",
    "strzyżów", "strzyzow",
    "tarnobrzeg",
    "tyczyn",
    "ulanów", "ulanow",
    "ustrzyki dolne",
    "zagórz", "zagorz",
    "zaklików", "zaklikow",

    # ==================================================================
    # Województwo podlaskie (Podlasie)
    # ==================================================================
    "augustów", "augustow",
    "białystok", "bialystok",
    "bielsk podlaski",
    "brańsk", "bransk",
    "choroszcz",
    "czarna białostocka", "czarna bialostocka",
    "czyżew", "czyzew",
    "dąbrowa białostocka", "dabrowa bialostocka",
    "drohiczyn",
    "goniądz", "goniadz",
    "grajewo",
    "hajnówka", "hajnowka",
    "jedwabne",
    "kleszczele",
    "knyszyn",
    "kolno",
    "krynki",
    "lipsk",
    "łapy", "lapy",
    "łomża", "lomza",
    "mielnik",
    "mońki", "monki",
    "nowogród", "nowogrod",
    "rajgród", "rajgrod",
    "sejny",
    "siemiatycze",
    "sokółka", "sokolka",
    "stawiski",
    "suchowola",
    "supraśl", "suprasl",
    "suwałki", "suwalki",
    "szczuczyn",
    "szepietowo",
    "tykocin",
    "wasilków", "wasilkow",
    "wysokie mazowieckie",
    "wizna",
    "zabłudów", "zabludow",
    "zambrów", "zambrow",

    # ==================================================================
    # Województwo pomorskie (Pomeranian)
    # ==================================================================
    "brusy",
    "bytów", "bytow",
    "chojnice",
    "czarne",
    "człuchów", "czluchow",
    "czersk",
    "debrzno",
    "dzierzgoń", "dzierzgon",
    "gdańsk", "gdansk",
    "gdynia",
    "gniew",
    "hel",
    "jastarnia",
    "kartuzy",
    "kępice", "kepice",
    "kościerzyna", "koscierzyna",
    "krynica morska",
    "kwidzyń", "kwidzyn",
    "lębork", "lebork",
    "łeba",
    "malbork",
    "miastko",
    "nowy dwór gdański", "nowy dwor gdanski",
    "nowy staw",
    "pelplin",
    "prabuty",
    "pruszcz gdański", "pruszcz gdanski",
    "puck",
    "reda",
    "rumia",
    "skarszewy",
    "skórcz", "skorcz",
    "słupsk", "slupsk",
    "sopot",
    "starogard gdański", "starogard gdanski",
    "sztum",
    "tczew",
    "ustka",
    "wejherowo",
    "władysławowo", "wladyslawowo",
    "żukowo", "zukowo",

    # ==================================================================
    # Województwo śląskie (Silesian / Śląsk)
    # ==================================================================
    "będzin", "bedzin",
    "bielsko-biała", "bielsko-biala", "bielsko biała", "bielsko biala",
    "bieruń", "bierun",
    "blachownia",
    "bytom",
    "chorzów", "chorzow",
    "cieszyn",
    "czechowice-dziedzice",
    "czeladź", "czeladz",
    "czerwionka-leszczyny",
    "częstochowa", "czestochowa",
    "dąbrowa górnicza", "dabrowa gornicza",
    "gliwice",
    "imielin",
    "jaworzno",
    "jastrzębie-zdrój", "jastrzebie-zdroj", "jastrzębie zdrój", "jastrzebie zdroj",
    "kalety",
    "katowice",
    "kłobuck", "klobuck",
    "knurów", "knurow",
    "koniecpol",
    "koziegłowy", "kozieglowy",
    "krzanowice",
    "krzepice",
    "kuźnia raciborska", "kuznia raciborska",
    "lędziny", "ledziny",
    "lubliniec",
    "łaziska górne", "laziska gorne",
    "łazy", "lazy",
    "miasteczko śląskie", "miasteczko slaskie",
    "mikołów", "mikolow",
    "mysłowice", "myslowice",
    "myszków", "myszkow",
    "ogrodzieniec",
    "orzesze",
    "piekary śląskie", "piekary slaskie",
    "pilica",
    "poręba", "poreba",
    "pszczyna",
    "pszów", "pszow",
    "pyskowice",
    "racibórz", "raciborz",
    "radlin",
    "radzionków", "radzionkow",
    "ruda śląska", "ruda slaska",
    "rybnik",
    "rydułtowy", "rydultowy",
    "siemianowice śląskie", "siemianowice slaskie",
    "siewierz",
    "skoczów", "skoczow",
    "sławków", "slawkow",
    "sosnowiec",
    "sośnicowice", "sosnicowice",
    "strumień", "strumien",
    "szczekociny",
    "szczyrk",
    "świętochłowice", "swietochlowice",
    "tarnowskie góry", "tarnowskie gory",
    "toszek",
    "tychy",
    "ustroń", "ustron",
    "wisła", "wisla",
    "wojkowice",
    "wodzisław śląski", "wodzislaw slaski",
    "zabrze",
    "zawiercie",
    "żarki", "zarki",
    "żory", "zory",
    "żywiec", "zywiec",

    # ==================================================================
    # Województwo świętokrzyskie (Świętokrzyskie / Holy Cross)
    # ==================================================================
    "busko-zdrój", "busko-zdroj", "busko zdrój", "busko zdroj",
    "chęciny", "checiny",
    "chmielnik",
    "ćmielów", "cmielow",
    "daleszyce",
    "działoszyce", "dzialoszyce",
    "jędrzejów", "jedrzejow",
    "kazimierza wielka",
    "kielce",
    "końskie", "konskie",
    "koprzywnica",
    "kunów", "kunow",
    "łagów", "lagow",
    "małogoszcz", "malogoszcz",
    "morawica",
    "nowa słupia", "nowa slupia",
    "opatów", "opatow",
    "osiek",
    "ostrowiec świętokrzyski", "ostrowiec swietokrzyski",
    "ożarów", "ozarow",
    "pińczów", "pinczow",
    "połaniec", "polaniec",
    "sandomierz",
    "sędziszów", "sedziszow",
    "skarżysko-kamienna", "skarzysko-kamienna", "skarżysko kamienna", "skarzysko kamienna",
    "skalbmierz",
    "starachowice",
    "staszów", "staszow",
    "stąporków", "staporkow",
    "stopnica",
    "suchedniów", "suchedniow",
    "szydłów", "szydlow",
    "włoszczowa", "wloszczowa",
    "wąchock", "wachock",
    "zawichost",

    # ==================================================================
    # Województwo warmińsko-mazurskie (Warmian-Masurian)
    # ==================================================================
    "barczewo",
    "bartoszyce",
    "biała piska", "biala piska",
    "biskupiec",
    "bisztynek",
    "braniewo",
    "dobre miasto",
    "działdowo", "dzialdowo",
    "elbląg", "elblag",
    "ełk", "elk",
    "frombork",
    "giżycko", "gizycko",
    "gołdap", "goldap",
    "górowo iławeckie", "gorowo ilaweckie",
    "iława", "ilawa",
    "jeziorany",
    "kętrzyn", "ketrzyn",
    "kisielice",
    "korsze",
    "lidzbark",
    "lidzbark warmiński", "lidzbark warminski",
    "lubawa",
    "mikołajki", "mikolajki",
    "młynary", "mlynary",
    "morąg", "morag",
    "mrągowo", "mragowo",
    "nidzica",
    "nowe miasto lubawskie",
    "olecko",
    "olsztyn",
    "olsztynek",
    "orneta",
    "orzysz",
    "ostróda", "ostroda",
    "pasłęk", "paslek",
    "pasym",
    "pieniężno", "pieniezno",
    "pisz",
    "reszel",
    "ruciane-nida",
    "ryn",
    "sępopol", "sepopol",
    "susz",
    "szczytno",
    "tolkmicko",
    "węgorzewo", "wegorzewo",
    "zalewo",

    # ==================================================================
    # Województwo wielkopolskie (Greater Poland / Wielkopolska)
    # ==================================================================
    "borek wielkopolski",
    "buk",
    "chodzież", "chodziez",
    "czarnków", "czarnkow",
    "czempiń", "czempin",
    "dąbie", "dabie",
    "dobra",
    "dobrzyca",
    "gniezno",
    "golina",
    "gostyń", "gostyn",
    "grodzisk wielkopolski",
    "jaraczewo",
    "jarocin",
    "kalisz",
    "kępno", "kepno",
    "kleczew",
    "kłecko", "klecko",
    "kłodawa", "klodawa",
    "kobylin",
    "kołaczyce", "kolaczyce",
    "koło", "kolo",
    "konin",
    "kostrzyn",
    "kościan", "koscian",
    "koźmin wielkopolski", "kozmin wielkopolski",
    "kórnik", "kornik",
    "krotoszyn",
    "krobia",
    "książ wielkopolski", "ksiaz wielkopolski",
    "leszno",
    "luboń", "lubon",
    "lwówek", "lwowek",
    "łobżenica", "lobzenica",
    "margonin",
    "mikstat",
    "miłosław", "miloslaw",
    "mosina",
    "murowana goślina", "murowana goslina",
    "nekla",
    "nowe skalmierzyce",
    "nowy tomyśl", "nowy tomysl",
    "oborniki",
    "odolanów", "odolanow",
    "opalenica",
    "ostrów wielkopolski", "ostrow wielkopolski",
    "ostroróg", "ostrorog",
    "ostrzeszów", "ostrzeszow",
    "piła", "pila",
    "pleszew",
    "pniewy",
    "pobiedziska",
    "pogorzela",
    "poniec",
    "poznań", "poznan",
    "przedecz",
    "pudliszki",
    "pyzdry",
    "rakoniewice",
    "rawicz",
    "rogoźno", "rogozno",
    "rychwał", "rychwal",
    "rydzyna",
    "sieraków", "sierakow",
    "skoki",
    "słupca", "slupca",
    "sompolno",
    "stawiszyn",
    "stęszew", "steszew",
    "swarzędz", "swarzedz",
    "szamotuły", "szamotuly",
    "śmigiel", "smigiel",
    "śrem", "srem",
    "środa wielkopolska", "sroda wielkopolska",
    "trzcianka",
    "trzemeszno",
    "tuliszków", "tuliszkow",
    "turek",
    "ujście", "ujscie",
    "wągrowiec", "wagrowiec",
    "wieruszów", "wieruszow",
    "witkowo",
    "wolsztyn",
    "września", "wrzesnia",
    "wyrzysk",
    "wysoka",
    "zagórów", "zagorow",
    "zbąszyń", "zbaszyn",
    "złotów", "zlotow",
    "żerków", "zerkow",

    # ==================================================================
    # Województwo zachodniopomorskie (West Pomeranian)
    # ==================================================================
    "barlinek",
    "barwice",
    "białogard", "bialogard",
    "biały bór", "bialy bor",
    "bobolice",
    "borne sulinowo",
    "cedynia",
    "chociwel",
    "chojna",
    "choszczno",
    "cybinka",
    "czaplinek",
    "darłowo", "darlowo",
    "dębno", "debno",
    "dobra",
    "dobrzany",
    "drawno",
    "drawsko pomorskie",
    "dziwnów", "dziwnow",
    "golczewo",
    "goleniów", "goleniow",
    "gryfice",
    "gryfino",
    "ińsko", "insko",
    "kamień pomorski", "kamien pomorski",
    "karlino",
    "kołobrzeg", "kolobrzeg",
    "koszalin",
    "lipiany",
    "łobez", "lobez",
    "maszewo",
    "mielno",
    "międzychód", "miedzychod",
    "międzyzdroje", "miedzyzdroje",
    "mieszkowice",
    "moryń", "moryn",
    "myślibórz", "mysliborz",
    "nowe warpno",
    "nowogard",
    "pelczyce",
    "płoty", "ploty",
    "polanów", "polanow",
    "police",
    "połczyn-zdrój", "polczyn-zdroj", "połczyn zdrój", "polczyn zdroj",
    "pyrzyce",
    "recz",
    "resko",
    "rewal",
    "sianów", "sianow",
    "sławno", "slawno",
    "sławoborze", "slawoborze",
    "stargard",
    "suchań", "suchan",
    "szczecin",
    "szczecinek",
    "świdwin", "swidwin",
    "świnoujście", "swinoujscie",
    "trzcińsko-zdrój", "trzcinsko-zdroj", "trzcińsko zdrój", "trzcinsko zdroj",
    "trzebiatów", "trzebiatow",
    "tuczno",
    "tychowo",
    "wałcz", "walcz",
    "węgorzyno", "wegorzyno",
    "wolin",
    "złocieniec", "zlocieniec",

    # ==================================================================
    # Additional tourist/resort towns and common transaction locations
    # (may overlap with cities above — set deduplicates automatically)
    # ==================================================================
    "hel",
    "jastarnia",
    "łeba", "leba",
    "krynica morska",
    "międzyzdroje", "miedzyzdroje",
    "ustka",
    "darłowo", "darlowo",
    "kołobrzeg", "kolobrzeg",
    "władysławowo", "wladyslawowo",
    "ustroń", "ustron",
    "wisła", "wisla",
    "szczyrk",
    "zakopane",
    "karpacz",
    "szklarska poręba", "szklarska poreba",
    "rewal",
    "mielno",
    "dziwnów", "dziwnow",
    "krynica-zdrój", "krynica-zdroj", "krynica zdrój", "krynica zdroj",
    "rabka-zdrój", "rabka-zdroj", "rabka zdrój", "rabka zdroj",
    "szczawnica",
    "muszyna",
    "piwniczna-zdrój", "piwniczna-zdroj",
    "kudowa-zdrój", "kudowa-zdroj",
    "polanica-zdrój", "polanica-zdroj",
    "duszniki-zdrój", "duszniki-zdroj",
    "lądek-zdrój", "ladek-zdroj",
    "ciechocinek",
    "nałęczów", "naleczow",
    "augustów", "augustow",
    "mikołajki", "mikolajki",
    "giżycko", "gizycko",
    "mrągowo", "mragowo",
    "pisz",
    "ruciane-nida",

    # ==================================================================
    # Additional cities across voivodeships (supplementary)
    # Ensures full coverage of all cities with municipal rights
    # ==================================================================

    # Dolnośląskie — additional
    "chocianów", "chocianow",
    "leszno",
    "niemcza",
    "olszyna",
    "prochowice",
    "siechnice",
    "stronie śląskie", "stronie slaskie",
    "bardo",
    "konstancin-jeziorna",
    "ziębice", "ziebice",
    "żórawina", "zorawina",

    # Kujawsko-pomorskie — additional
    "kcynia",
    "lubraniec",
    "piotrków kujawski", "piotrkow kujawski",
    "więcbork", "wiecbork",
    "izbica kujawska",

    # Lubelskie — additional
    "kock",
    "ostrów lubelski", "ostrow lubelski",
    "urzędów", "urzedow",
    "bełżyce", "belzyce",
    "końskowola", "konskowola",

    # Łódzkie — additional
    "łęczyca", "leczyca",
    "łask", "lask",
    "poddębice", "poddebice",
    "złoczew", "zloczew",
    "żychlin", "zychlin",
    "stryków", "strykow",
    "sulejów", "sulejow",
    "warta",
    "tuszyn",

    # Małopolskie — additional
    "szczucin",
    "proszowice",
    "skała", "skala",
    "sułkowice", "sulkowice",

    # Mazowieckie — additional
    "warka",
    "żuromin", "zuromin",
    "myszyniec",
    "mogielnica",
    "mordy",
    "tarczyn",
    "góra kalwaria", "gora kalwaria",
    "glinojeck",
    "chlewiska",
    "jedlińsk", "jedlinsk",
    "magnuszew",
    "stoczek łukowski", "stoczek lukowski",

    # Opolskie — additional
    "strzeleczki",
    "zawadzkie",
    "zdzieszowice",

    # Podkarpackie — additional
    "nowa sarzyna",
    "oleszyce",
    "radymno",
    "sieniawa",
    "tyczyn",

    # Podlaskie — additional
    "szepietowo",
    "wizna",
    "jedwabne",
    "kleszczele",
    "lipsk",
    "mielnik",
    "nowogród", "nowogrod",

    # Pomorskie — additional
    "nowy staw",
    "pelplin",
    "prabuty",
    "skórcz", "skorcz",
    "gniew",
    "czarne",
    "czersk",
    "debrzno",

    # Śląskie — additional
    "kalety",
    "imielin",
    "wojkowice",
    "sośnicowice", "sosnicowice",
    "toszek",
    "krzanowice",
    "krzepice",
    "koniecpol",
    "pilica",
    "siewierz",
    "ogrodzieniec",
    "szczekociny",
    "blachownia",

    # Świętokrzyskie — additional
    "stopnica",
    "skalbmierz",
    "osiek",
    "koprzywnica",
    "zawichost",
    "nowa słupia", "nowa slupia",
    "morawica",
    "daleszyce",

    # Warmińsko-mazurskie — additional
    "ryn",
    "sępopol", "sepopol",
    "susz",
    "zalewo",
    "tolkmicko",
    "jeziorany",
    "kisielice",
    "korsze",
    "pasym",

    # Wielkopolskie — additional
    "pyzdry",
    "stawiszyn",
    "sompolno",
    "przedecz",
    "dobra",
    "kobylin",
    "pogorzela",
    "poniec",
    "krobia",
    "borek wielkopolski",
    "mikstat",
    "rydzyna",
    "rakoniewice",
    "skoki",
    "nekla",
    "witkowo",
    "wysoka",
    "wyrzysk",
    "margonin",
    "golina",
    "kleczew",
    "dąbie", "dabie",
    "dobrzyca",

    # Zachodniopomorskie — additional
    "barwice",
    "bobolice",
    "borne sulinowo",
    "cedynia",
    "chociwel",
    "chojna",
    "dobrzany",
    "drawno",
    "golczewo",
    "ińsko", "insko",
    "nowe warpno",
    "tychowo",
    "tuczno",
    "pelczyce",

    # ==================================================================
    # Trójmiasto & common aliases
    # ==================================================================
    "trójmiasto", "trojmiasto",
}
